import json
from pathlib import Path

import gymnasium as gym
import numpy as np

from lamps.independent_loss import CACHE_KIND, DEFAULT_CACHE_DIR, cache_path
from lamps.posterior_cache import LogLossPosteriorCache

from .base import BaseObserver


class PerModelLogLossGPObserver(BaseObserver):
    """Per-model next-epoch log-loss GP posterior mean/std."""

    NAME = "per_model_gp/eval_log_loss_posterior"

    def __init__(self, env, cache_dir: str | Path = DEFAULT_CACHE_DIR):
        super().__init__(env)
        path = cache_path(cache_dir, env.repository.experiment, env.dataset)
        cache = LogLossPosteriorCache.load(path)
        metadata = json.loads(cache.metadata_json)
        if metadata.get("kind") != CACHE_KIND:
            raise ValueError(
                "Cache was not generated by the strictly independent estimator."
            )
        if cache.experiment != env.repository.experiment or cache.dataset != env.dataset:
            raise ValueError(
                "Per-model GP posterior cache identity does not match the environment."
            )

        cache_indices = {model: i for i, model in enumerate(cache.models.tolist())}
        missing_models = [model for model in self.models if model not in cache_indices]
        if missing_models:
            raise ValueError(
                f"Per-model GP posterior cache is missing models: {missing_models}"
            )
        order = np.asarray([cache_indices[model] for model in self.models])
        self.posterior_mean = cache.mean[order]
        self.posterior_std = cache.std[order]
        if not np.array_equal(cache.available_epochs[order], self.env.available_epochs):
            raise ValueError(
                "Per-model GP posterior cache epochs do not match the repository."
            )

    def to_space(self) -> gym.Space:
        low = np.broadcast_to(
            np.asarray([-15.0, 0.0], dtype=np.float32), (self.num_models, 2)
        ).copy()
        high = np.broadcast_to(
            np.asarray([15.0, 15.0], dtype=np.float32), (self.num_models, 2)
        ).copy()
        return gym.spaces.Box(low=low, high=high, dtype=np.float32)

    def observe(self):
        model_indices = np.arange(self.num_models)
        epochs = np.asarray(self.env.epoch_counts, dtype=np.intp)
        return np.column_stack(
            (
                self.posterior_mean[model_indices, epochs],
                self.posterior_std[model_indices, epochs],
            )
        ).astype(np.float32, copy=False)
